repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: 'stable'
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 'stable'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        language_version: python3.8
  - repo: https://github.com/asottile/seed-isort-config
    rev: 'v2.1.0'
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'stable'
    hooks:
      - id: isort
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'stable'
    hooks:
      - id: pylint
        args:
          - --disable=C0114,C0115,C0116
        language_version: python3.8